### PR TITLE
Adding docker

### PR DESCRIPTION
**Pull request by nuriel77**
Adding a Dockerfile and instructions

### CODE REVIEW

**Comment by IoTMOD** [comment]
Thanks for the PR :)

Could you try to add a 
```
- name: Build HORNET Docker image
      run: docker build -t hornet:latest .
```
step to .github/workflows/build.yml

So build.yml will look like this:
```
name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.5
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build HORNET
      run: go build -v .

    - name: Build HORNET Docker image
      run: docker build -t hornet:latest .
```
I'm not sure if it is working. If it fails, just remove it again and I'll merge this PR anyway

**Comment by nuriel77** [comment]
@IoTMOD I am going over [this documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action) see if I can get it working as proposed here.

**Comment by nuriel77** [comment]
@IoTMOD finally, seems working. Added some minutes to total build time :)

**Comment by IoTMOD** [comment]
Perfect, thank you!
Yes, but that's OK for now 👍

**Review by IoTMOD — APPROVED** [review]

**Pull request merged**
