### PR TITLE
Docker/custom uid gid

### PR DESCRIPTION
**Pull request by nuriel77**
# Description

Instead of hard-coding the UID:GID used to run hornet in the Dockerfile, set those as ARGs, allowing a user to set custom values during docker build.

Fixes https://github.com/gohornet/hornet/issues/957

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Fix

# How Has This Been Tested?

Was tested by:
- building the image with a custom UID:GID on a Hornet node.
- chown the existing hornet directories with the custom UID:GID
- run hornet

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have tested my code extensively
- [x] I have selected the `develop` branch as the target branch

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

**Comment by thezepter** [comment]
Thank you ! But how can i build a container of the dev brench ? (Sorry for my bad english) German is my main language.
There is no DEV Version in docker Hub ?!  https://hub.docker.com/r/gohornet/hornet/tags?page=1&ordering=last_updated
The "latest" Version is too old

**Comment by muXxer** [comment]
@thezepter 
I don't know how your synology stuff works, since I don't own one.
But normally you have the Dockerfile in our repository, which is used to create the container.

Clone the repository, and let docker built the container.

So I guess you need access via SSH to your NAS. Not possible via web interface I guess.

**Comment by thezepter** [comment]
Yes. i use only the concole via ssh. But how can i clone the dev branch from guthub ?`

`git clone https://github.com/gohornet/hornet && cd hornet`  <-- this pulls the master branch.

`git clone https://github.com/gohornet/hornet/tree/develop && cd hornet` <-- doesnt work. 

I´ve no idea how to pull the dev branch. sorry

**Comment by nuriel77** [comment]
@thezepter you are correct about the first two steps:
1. clone the repository `git clone https://github.com/gohornet/hornet`
2. enter (cd) the directory `cd hornet`
3. checkout to the development branch `git checkout develop`

Then you will have the correct Dockerfile to use for the build.

**Comment by thezepter** [comment]
Thank you !!! That works great with checkout develop !
But the same permission error for me after run command.

1. i create a user "iotanode" with UID:1034 & GID: 100
2. i changed the UID and GID in the Dockerfile
3. docker run = permission denied.

image


is this command after checkout the devekope branch correct ?

`docker build -f docker/Dockerfile -t hornet:latest .`  <-- "latest" makes me wonder, but there is no TAG for a dev version

**Comment by nuriel77** [comment]
> docker build -f docker/Dockerfile -t hornet:latest . <-- "latest" makes me wonder

@thezepter `latest` is just the image's tag. Since you're building from development branch you could tag it `dev`.

About the UID:GID I need to understand several things:
1. what command exactly did you use to build the new docker image? (I am wondering specifically about which UID and GID did you set as build arguments?)
2. are you mounting the `config,json` from your storage into the container? Can you run `ls -ln` on the file on your storage to view the numeric UID:GID?
3. can you share the full docker run command you're using?

**Comment by thezepter** [comment]
Thanks in advance for your support. With docker build I have never done much so far only loaded and run.

1.
`git clone https://github.com/gohornet/hornet`

2.
`cd hornet`

3.
`git checkout develop`

4.
`docker build -f docker/Dockerfile --build-arg SET_UID=1034 --build-arg SET_GID=100 -t hornet:latest .`

5.
`docker run --rm -v /volume1/docker/iotahornetnode/config.json:/app/config.json:ro -v /volume1/docker/iotahornetnode/snapshots/mainnet:/app/snapshots/mainnet -v /volume1/docker/iotahornetnode/mainnetdb:/app/mainnetdb --name=hornet --net=host hornet:latest`


Yes i´m mounting the config.json from my Storage:
image

**Comment by nuriel77** [comment]
@thezepter I think what happened is that your build failed because GID is already allocated on the base docker image:
```
#7 14.49 addgroup: gid '100' in use
------
executor failed running [/bin/sh -c apk --no-cache add ca-certificates curl jq tini tar && update-ca-certificates 2>/dev/null || true && if [ "$TAG" = "latest" ];    then      HORNET_TAG=$(curl --retry 3 -f -s https://api.github.com/repos/${REPO}/releases/latest | jq -r .tag_name | tr -d 'v');    else      HORNET_TAG="${TAG//v}";    fi && echo "Downloading from https://github.com/${REPO}/releases/download/v${HORNET_TAG}/HORNET-${HORNET_TAG}_${OS}_${ARCH}.tar.gz ..." && curl -f -L --retry 3 "https://github.com/${REPO}/releases/download/v${HORNET_TAG}/HORNET-${HORNET_TAG}_${OS}_${ARCH}.tar.gz" -o /tmp/hornet.tgz && tar --wildcards --strip-components=1 -xf /tmp/hornet.tgz -C /app/ */hornet */config.json */config_comnet.json */config_devnet.json */peering.json && if [ "$ARCH" = "x86_64" ];    then      curl -f -L --retry 3 -o /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub;      curl -f -L --retry 3 -o glibc-2.30-r0.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk;      apk add glibc-2.30-r0.apk;      rm glibc-2.30-r0.apk;    fi && addgroup --gid $SET_GID hornet && adduser -h /app -s /bin/sh -G hornet -u $SET_UID -D hornet && chmod +x /app/hornet && chown hornet:hornet -R /app && rm /tmp/hornet.tgz && apk del jq curl]: exit code: 1
```
If you're missed this message, you might have proceeded to run docker with the older image and that's why the permission error.

I'd build the docker image using GID 1034, not 100. And because `config.json` has its user read bit enabled, hornet in the container should be able to read it.

Also note that you have executable bit enabled on the `json` files, that is not necessary. You can run `sudo chmod ug-x config.json peering.json` if that's possible on your storage (this isn't the root of the problem though, just something I've observed).
There's also extended attributes set on the files (the + at the end: ---+) which might also be enabling some execution bit for particular users/groups. Maybe the storage system is doing something weird with permissions, I don't know.

**Comment by thezepter** [comment]
hmmm wired ?!

docker version on my Synology is: 18.09.8

chmod works..
image


docker build result: (looks fine in my eyes)
image

Can I do without a local config.json and peering.json or do I need to customize anything at all ?
I just want to do something good for the community and run a node

I simply omitted the config from the run command... but there comes already the next authorization error.
image

**Comment by nuriel77** [comment]
> docker version on my Synology is: 18.09.8

Don't think this is relevant to what we've discussed so far.

You see "Returned a non-zero code 22" -> that is an error. Can't see all your output but should be somewhere what failed.

If you can chmod files on your Synology why not just `chmod 39999:39999 /path/to/files/*` and build and docker image without any UID:GID overrides?

**Comment by thezepter** [comment]
`chmod 39999:39999 /path/to/files/*` did´nt work  --> chmod: invalid mode: ‘39999:39999’

what worked is: 
`chown 39999:39999 /volume1/docker/iotahornetnode/*`

image

ok.. new build
`docker build -f docker/Dockerfile -t hornet:dev .`

run:
`docker run --rm -v /volume1/docker/iotahornetnode/config.json:/app/config.json:ro -v /volume1/docker/iotahornetnode/snapshots/mainnet:/app/snapshots/mainnet -v /volume1/docker/iotahornetnode/mainnetdb:/app/mainnetdb --name=hornet --net=host hornet:latest`

image

**Comment by nuriel77** [comment]
>chmod 39999:39999 /path/to/files/* did´nt work --> chmod: invalid mode: ‘39999:39999’

Sorry, my bad, it is `chown` 😂

**Comment by nuriel77** [comment]
You need to chown with -R (Recursive)

**Comment by thezepter** [comment]
`chown 39999:39999 /volume1/docker/iotahornetnode/* -R`
didn`t help. same Permission denied for the database like the screenshot

**Comment by nuriel77** [comment]
I don't know.
Try to login to the container:
```
docker run --rm -it -v /volume1/docker/iotahornetnode/config.json:/app/config.json:ro -v /volume1/docker/iotahornetnode/snapshots/mainnet:/app/snapshots/mainnet -v /volume1/docker/iotahornetnode/mainnetdb:/app/mainnetdb --entrypoint=/bin/sh --name=hornet --net=host hornet:latest
```
This should spawn a shell in it.
Then run the following commands:
`ls -l /app/config.json`
`ls -ld /app`
`ls -ld /app/mainnetdb`
`id`

**Comment by thezepter** [comment]
image


```
~ $ ls -l /app/config.json
-rw-rw----    1 hornet   hornet        3517 Mar 13 11:13 /app/config.json
```

```
~ $ ls -ld /app
drwxr-sr-x    1 hornet   hornet          94 Apr  8 13:36 /app
```

```
~ $ ls -ld /app/mainnetdb
d---------    1 hornet   hornet           0 Apr  8 10:33 /app/mainnetdb
```

```
~ $ id
uid=39999(hornet) gid=39999(hornet)
```

**Comment by nuriel77** [comment]
Note that the mainnetdb has no bits set:
```
~ $ ls -ld /app/mainnetdb
d---------    1 hornet   hornet           0 Apr  8 10:33 /app/mainnetdb
```
If you could find out why it gets mounted without any ownership bits?
On the source (storage) I saw it was `drwxrwx---`

**Comment by thezepter** [comment]
omg... i have no idea... thats very strange... yes the source has the correct bits

**Comment by thezepter** [comment]
I'm not going to give up that easily.
I think I know why it doesn't work that way.
(I still had an old "latest version" from the Docker Gui surface lying around from which he always started the container with the docker Run command. 

now I have started all over again.
All hornet builds deleted once again.

the docker Build Command returns an Error in line 62 (pastebin link see below)
it also doesn't matter if I use the dev or master branch. Docker build always throws the same error.

https://pastebin.com/32bGcM8N

`docker build -f docker/Dockerfile  -t hornet:latest .`

```
Downloading from https://github.com//releases/download/v/HORNET-__.tar.gz ...
curl: (22) The requested URL returned error: 404
```

this seems to abort the build, now when i want to run a docker run command it says no build exists.

any idea why the requested link returns a 404 ?

**Comment by nuriel77** [comment]
@thezepter can you check what is your current docker version?
I see that variables were not resolved during the build for some reason, I am suspecting that might have to do with your Docker version (see: `Downloading from https://github.com//releases/download/v/HORNET-__.tar.gz ...` missing the variables, they are empty)

In addition, I think it is a good idea to build the image using the latest version tag (0.5.6), see example https://github.com/gohornet/hornet/tree/develop/docker#build-specific-version

**Comment by thezepter** [comment]
docker version on my Synology is: 18.09.8 (no update available)

`docker build -f docker/Dockerfile --build-arg SET_UID=1026 --build-arg SET_GID=100 -t hornet:latest -t hornet:v0.5.6 --build-arg TAG=v0.5.6 .`

Same problem:  **Downloading from https://github.com//releases/download/v/HORNET-__.tar.gz**

https://pastebin.com/HqgqK27a

**Comment by nuriel77** [comment]
@thezepter 
This seems like an old version. Maybe it doesn't support ARG yet? I don't know.
Why don't you download the final image? https://hub.docker.com/r/iotaledger/hornet/tags?page=1&ordering=last_updated&name=v0.5.6

I see you're trying to build with GID 100 again, but as I mentioned last time this will conflict with an existing group.
I believe we've also concluded that you can `chown` the source directories and files on your storage system to UID:GID 39999, in which case I'd expect it to be able to run the original image from docker hub, without having to rebuild the image with custom UID:GID.

From my [comment](https://github.com/gohornet/hornet/pull/1007#issuecomment-815908804) we've concluded that your docker is somehow losing the permission bits on the directory. I think that is the root of the problem. Might be related to the outdated docker version. I don't know.

Did you try on Discord (hornet channel) to see if anyone else managed to get hornet running on the same storage system?

**Comment by thezepter** [comment]
Problems with args on synology.  if I interpret this correctly, you can solve this via ENV ?

Found this: https://gist.github.com/agross/614b3c85dcc152e258403f4c5d4273b7
and this: https://community.synology.com/enu/forum/11/post/135674

Oh hornet has a Discord Server.. nice ! I I'll see if I can find someone there with a synology. 
The UID and PID args were just a test. Even without them I get the same errors.

**Comment by nuriel77** [comment]
I don't know, you can try to modify the Dockerfile and set those ARG as ENV

**Comment by thezepter** [comment]
Changed ARG to ENV in the dockerfile. Now the Build is complete. But the Container won´t start. No error in Container log.

`docker build -f docker/Dockerfile  -t hornet:latest .`
---> bcfd25432d72
Successfully built bcfd25432d72
Successfully tagged hornet:latest
https://pastebin.com/SSAf016M

Thanks !! 

But I won't get any further, because I can't solve the problem with the permission bits. 
Cant start he container... no logs

----------    1 hornet   hornet        3517 Mar 13 11:13 /app/config.json
~ $ ls -ld /app
drwxr-sr-x    1 hornet   hornet         190 Apr 12 12:35 /app
~ $ ls -ld /app/mainnetdb
d---------    1 hornet   hornet           0 Apr 12 12:10 /app/mainnetdb


Probably this is because I can't create a user manually on my synology with the uid and gid 39999. And giving a GID and UID by variable in the build command doesn't work because I need the GID 100. Life is hard

**Comment by thezepter** [comment]
node is now running.

for fun i gave the docker folder "everyone" the permission to read and write and now i have no problems with the permissions.

**Pull request merged**
