### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by nuriel77**
# Changed
* default Dockerfile to use release binary
* keep using alpine and install glibc (only for x86_64)
* update instructions in DOCKER.md

# Added
* table of contents for DOCKER.md
* Instructions on how to run docker with local snapshots
* Dockerfiles for arm64 and armhf (using release binaries)

### CODE REVIEW

**Review by IoTMOD — COMMENTED** [review]
Does it make sense to add all Docker related files into one `docker` folder? 
So this folder would contain:
- DOCKER.md
- Dockerfile
- Dockerfile.arm64
- Dockerfile.armhf
- Dockerfile.goreleaser
- docker-compose.yml

And please point your PR to the `develop` branch as described in our new https://github.com/gohornet/hornet/blob/master/CONTRIBUTING.md

**Comment by nuriel77** [comment]
@IoTMOD the docker-compose.yml I left in the root. It makes it a little more complicated to move it in to docker/.
To work from docker/ the user would have to add some more arguments to the `docker-compose up` command (e.g. docker-compose.yml location and work dir).

**Comment by nuriel77** [comment]
@IoTMOD hmm not sure why the builds failed. I can't see what is the error?

**Comment by IoTMOD** [comment]
You have to edit the docker workflow as well (Dockerfile path):
https://github.com/gohornet/hornet/blob/master/.github/workflows/build_docker.yml

At least I didn't see this change, on mobile right now

**Comment by nuriel77** [comment]
@IoTMOD after having updated build_docker.yml, I get this error:
```
The following team project collection is stopped: uHCSTMDmnsNmRUhCGjbjofpIVmBamfRQYA356ywsx07eUbM2B5. Start the collection and then try again. Administrator Reason: Creating Collection Host
```

**Comment by IoTMOD** [comment]
@nuriel77 strange, I just had to restart the tests :smile:
Maybe due to the changes :thinking: 
Anyway it's working now :+1:

**Comment by nuriel77** [comment]
@IoTMOD awesome, thanks.

**Review by IoTMOD — APPROVED** [review]

**Comment by IoTMOD** [comment]
Thank you!

**Pull request merged**
